[x-csl-package]
; not change
remoteDir="."
localDir="Resources/plugins/IVAO_CSL/CSL"

[folders]
; additional folders prefixes
; content of remote folder <PilotUI> will be placed at <sim/Resources/plugins/ivao_pilot/PilotUI/data> locally. Will be create new if not exist.
PilotUI="Resources/plugins/ivao_pilot/PilotUI/data"
Resources="Resources/plugins/IVAO_CSL"
